<script>
  import { onMount } from 'svelte';
  import { loadFeed, sortNewest } from '$lib/newsData';

  let feed;
  let error = '';

  onMount(async () => {
    try {
      feed = await loadFeed();
    } catch (reason) {
      error = reason instanceof Error ? reason.message : 'Unable to load pipeline status.';
    }
  });

  $: sourceRows = feed
    ? Object.entries(feed.source_health || {})
        .map(([name, health]) => ({
          name,
          status: health?.status || health?.content_status || 'unknown',
          scope: health?.scope || '',
          updated: health?.last_success || health?.updated_at || ''
        }))
        .sort((a, b) => a.name.localeCompare(b.name))
    : [];

  $: recentCount = feed
    ? sortNewest(feed.stories || []).filter((story) => Date.now() - new Date(story.published || 0).getTime() < 60 * 60 * 1000).length
    : 0;
</script>

<svelte:head>
  <title>Pipeline | Forest City News</title>
</svelte:head>

<main class="app-page" id="main-content">
  <section class="shell">
    <header class="app-page-heading">
      <p class="eyebrow">System</p>
      <h1>Pipeline</h1>
      <p>A lightweight view of the feed generated by Scoop.</p>
    </header>

    {#if error}
      <div class="app-error">{error}</div>
    {:else if !feed}
      <div class="app-loading-grid">
        <div class="app-skeleton"></div>
        <div class="app-skeleton"></div>
        <div class="app-skeleton"></div>
      </div>
    {:else}
      <div class="pipeline-stats">
        <div><strong>{feed.stories.length}</strong><span>stories indexed</span></div>
        <div><strong>{sourceRows.length}</strong><span>sources tracked</span></div>
        <div><strong>{recentCount}</strong><span>stories in the last hour</span></div>
      </div>

      <div class="source-health">
        {#each sourceRows as source}
          <div class="source-health-row">
            <span><strong>{source.name}</strong><small>{source.scope || 'unscoped'}</small></span>
            <span class={`health-state health-${source.status}`}>{source.status}</span>
          </div>
        {/each}
      </div>
    {/if}
  </section>
</main>

<style>
  .pipeline-stats {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 12px;
    margin-bottom: 28px;
  }

  .pipeline-stats div {
    padding: 22px;
    border-radius: 16px;
    background: var(--surface-subtle);
  }

  .pipeline-stats strong,
  .pipeline-stats span {
    display: block;
  }

  .pipeline-stats strong {
    font-size: 30px;
    letter-spacing: -.04em;
  }

  .pipeline-stats span {
    margin-top: 3px;
    color: var(--text-tertiary);
    font-size: 12px;
  }

  .source-health {
    display: grid;
    gap: 7px;
  }

  .source-health-row {
    min-height: 58px;
    padding: 0 16px;
    border-radius: 14px;
    background: var(--surface-subtle);
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 20px;
  }

  .source-health-row strong,
  .source-health-row small {
    display: block;
  }

  .source-health-row small {
    margin-top: 2px;
    color: var(--text-tertiary);
  }

  .health-state {
    color: var(--accent, #34c759);
    font-size: 12px;
    font-weight: 700;
    text-transform: capitalize;
  }

  @media (max-width: 620px) {
    .pipeline-stats {
      grid-template-columns: 1fr;
    }
  }
</style>
