from __future__ import annotations

"""Final publisher hygiene guard for Scoop article bodies.

The extractors are intentionally source-agnostic, but publisher pages sometimes
serialize UI, recommendation modules or reader-service metadata as if it were
article prose. This pass runs after extraction and removes only high-confidence
publisher chrome while preserving real paragraphs, headings, lists and images.
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
NEWS_PATH = ROOT / "data" / "news.json"
HYGIENE_SCHEMA = 2

IMAGE_SUMMARY_RE = re.compile(r"^image\s+\d+(?:\s*,\s*\d+)*(?:\s*[:|]|$)", re.I)
CBC_DURATION_RE = re.compile(r"^duration\s+\d{1,2}:\d{2}(?::\d{2})?$", re.I)
CBC_TIME_AGO_RE = re.compile(r"^\d+\s+(?:minutes?|hours?)\s+ago$", re.I)
CBC_WATCH_RE = re.compile(r"^(?:watch|video)\s*[|:]", re.I)
CBC_PHOTO_CREDIT_RE = re.compile(r"\([^()]{2,120}/CBC(?:\s+News)?\)\s*$", re.I)
CBC_BYLINE_RE = re.compile(r"^[A-Z][^|•·]{1,90}\s*[|•·]\s*CBC\s+News(?:\s*[|•·].*)?$", re.I)
CBC_POSTED_RE = re.compile(r"^(?:posted|published|last updated)\s*:", re.I)

GLOBE_TERMINAL_HEADINGS = {
    "diversions",
    "puzzles",
    "puzzles and games",
    "games",
    "latest videos",
    "more videos",
    "watch more videos",
}

GLOBAL_UI_EXACT = {
    "watch",
    "previous video",
    "next video",
    "recommended video",
    "stick to the facts",
    "stick to facts",
    "hide message bar",
}


def clean(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def key(value: Any) -> str:
    text = clean(value).lower().replace("’", "'")
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9']+", " ", text)).strip()


def words(value: Any) -> int:
    return len(re.findall(r"\b\w+[’'-]?\w*\b", clean(value)))


def item_text(value: Any) -> str:
    if isinstance(value, dict):
        return clean(value.get("text") or value.get("label") or value.get("title"))
    return clean(value)


def block_text(block: dict[str, Any]) -> str:
    if block.get("type") == "list":
        return " ".join(item_text(item) for item in block.get("items", []) if item_text(item))
    for field in ("text", "title", "label", "name", "caption", "alt"):
        if block.get(field):
            return clean(block.get(field))
    return ""


def source_name(story: dict[str, Any]) -> str:
    return clean(story.get("source")).lower()


def source_is_citynews(story: dict[str, Any]) -> bool:
    return "citynews" in source_name(story)


def source_is_cbc(story: dict[str, Any]) -> bool:
    return "cbc" in source_name(story)


def source_is_global(story: dict[str, Any]) -> bool:
    return "global news" in source_name(story)


def source_is_star(story: dict[str, Any]) -> bool:
    source = source_name(story)
    return "toronto star" in source or source == "the star"


def source_is_globe(story: dict[str, Any]) -> bool:
    return "globe and mail" in source_name(story)


def image_summary_list(block: dict[str, Any]) -> bool:
    if block.get("type") != "list":
        return False
    items = [item_text(item) for item in block.get("items", []) if item_text(item)]
    if len(items) < 2:
        return False
    matches = sum(1 for item in items if IMAGE_SUMMARY_RE.match(item))
    return matches >= 2 and matches / len(items) >= 0.60


def citynews_ui(value: Any) -> bool:
    normalized = key(value)
    if normalized in {"keep it factual", "keep reading"}:
        return True
    if normalized.startswith("add citynews") and "source on google" in normalized:
        return True
    if normalized.startswith("add as a preferred source on google"):
        return True
    if normalized in {"citynews everywhere", "680 news radio toronto", "rogers sports media toronto"}:
        return True
    return False


def global_ui(value: Any) -> bool:
    normalized = key(value)
    if normalized in GLOBAL_UI_EXACT:
        return True
    if normalized.startswith("add global news") and "preferred source on google" in normalized:
        return True
    if normalized.startswith("add global news") and "source on google" in normalized:
        return True
    return False


def cbc_audio_ui(value: Any) -> bool:
    normalized = key(value)
    if normalized == "listen to this article":
        return True
    if re.fullmatch(r"estimated \d+ minutes?", normalized):
        return True
    if "audio version of this article is generated by ai based technology" in normalized:
        return True
    if "mispronunciations can occur" in normalized and "review and improve" in normalized:
        return True
    return False


def cbc_metadata(value: Any) -> bool:
    text = clean(value)
    return bool(CBC_BYLINE_RE.match(text) or CBC_POSTED_RE.match(text))


def cbc_photo_caption(value: Any) -> bool:
    text = clean(value)
    return 6 <= words(text) <= 70 and bool(CBC_PHOTO_CREDIT_RE.search(text))


def short_promo_heading(value: Any) -> bool:
    text = clean(value)
    count = words(text)
    if count < 2 or count > 22 or len(text) > 220:
        return False
    return not bool(re.search(r"[.!?][\"'’”)]?$", text))


def cbc_video_ranges(blocks: list[dict[str, Any]]) -> set[int]:
    """Return high-confidence CBC text-video module indexes."""
    remove: set[int] = set()
    for index, block in enumerate(blocks):
        if not CBC_DURATION_RE.match(block_text(block)):
            continue

        start = index
        cursor = index - 1
        back_limit = max(-1, index - 4)
        while cursor > back_limit:
            candidate = blocks[cursor]
            text = block_text(candidate)
            if candidate.get("type") in {"image", "media"}:
                start = cursor
                cursor -= 1
                continue
            if CBC_TIME_AGO_RE.match(text) or CBC_WATCH_RE.match(text) or short_promo_heading(text):
                start = cursor
                cursor -= 1
                continue
            break

        end = index + 1
        summary_consumed = False
        forward_limit = min(len(blocks), index + 5)
        while end < forward_limit:
            candidate = blocks[end]
            text = block_text(candidate)
            if candidate.get("type") in {"image", "media"}:
                end += 1
                continue
            if CBC_TIME_AGO_RE.match(text) or CBC_DURATION_RE.match(text) or CBC_WATCH_RE.match(text):
                end += 1
                continue
            if not text:
                end += 1
                continue
            if not summary_consumed and (words(text) >= 12 or len(text) >= 80):
                summary_consumed = True
                end += 1
            break

        remove.update(range(start, end))
    return remove


def substantive_story_text(value: Any) -> bool:
    text = clean(value)
    return words(text) >= 12 and len(text) >= 70 and bool(re.search(r"[.!?][\"'’”)]?$", text))


def star_ui(value: Any) -> bool:
    normalized = key(value)
    if normalized == "you have permission to edit this article":
        return True
    if normalized.startswith("site search"):
        return True
    if normalized in {"today's paper", "todays paper"}:
        return True
    if normalized.startswith("play now") and "lottery" in normalized:
        return True
    return False


def paragraphs_from_blocks(blocks: list[dict[str, Any]]) -> list[str]:
    output: list[str] = []
    for block in blocks:
        kind = block.get("type")
        if kind in {"paragraph", "quote"} and block.get("text"):
            output.append(clean(block.get("text")))
        elif kind == "list":
            output.extend(item_text(item) for item in block.get("items", []) if item_text(item))
    return output


def rebuild(story: dict[str, Any], blocks: list[dict[str, Any]], removed: list[str]) -> None:
    paragraphs = paragraphs_from_blocks(blocks)
    story["content_blocks"] = blocks
    story["paragraphs"] = paragraphs
    story["content"] = "\n\n".join(paragraphs)
    story["word_count"] = sum(words(paragraph) for paragraph in paragraphs)
    story["publisher_hygiene_schema"] = HYGIENE_SCHEMA
    story["publisher_hygiene_removed"] = sorted(set(removed))
    story["publisher_hygiene_cleaned_at"] = datetime.now(timezone.utc).isoformat()


def clean_story(story: dict[str, Any]) -> bool:
    raw_blocks = story.get("content_blocks") if isinstance(story.get("content_blocks"), list) else []
    if raw_blocks:
        blocks = [dict(block) for block in raw_blocks if isinstance(block, dict)]
    else:
        raw_paragraphs = story.get("paragraphs") if isinstance(story.get("paragraphs"), list) else []
        blocks = [
            {"type": "paragraph", "text": clean(paragraph)}
            for paragraph in raw_paragraphs
            if clean(paragraph)
        ]
    if not blocks:
        return False

    removed: list[str] = []
    cbc_video = cbc_video_ranges(blocks) if source_is_cbc(story) else set()
    out: list[dict[str, Any]] = []
    star_chrome = False

    for index, block in enumerate(blocks):
        text = block_text(block)
        normalized = key(text)

        if image_summary_list(block) or (text and IMAGE_SUMMARY_RE.match(text)):
            removed.append("jina-image-summary")
            continue

        if source_is_globe(story) and block.get("type") == "heading" and normalized in GLOBE_TERMINAL_HEADINGS:
            removed.append("globe-diversions-tail")
            break

        if source_is_citynews(story) and citynews_ui(text):
            removed.append("citynews-publisher-promo")
            continue

        if source_is_global(story):
            # Global's page embeds frequently survive extraction as non-functional
            # cross-origin players. Scoop cannot reliably render those transport
            # wrappers, so keep the editorial text and photos but omit the player.
            if block.get("type") == "media":
                removed.append("global-inline-media")
                continue
            if global_ui(text):
                removed.append("global-publisher-ui")
                continue

        if source_is_cbc(story):
            if index in cbc_video:
                removed.append("cbc-video-promo")
                continue
            if cbc_audio_ui(text):
                removed.append("cbc-audio-ui")
                continue
            if cbc_metadata(text):
                removed.append("cbc-page-metadata")
                continue
            if block.get("type") in {"paragraph", "quote"} and cbc_photo_caption(text):
                if not clean(story.get("image_caption")):
                    story["image_caption"] = text[:400]
                removed.append("cbc-photo-caption")
                continue
            if CBC_WATCH_RE.match(text):
                removed.append("cbc-video-label")
                continue

        if source_is_star(story):
            if star_ui(text):
                star_chrome = True
                removed.append("star-navigation")
                continue
            if star_chrome:
                if substantive_story_text(text):
                    star_chrome = False
                else:
                    removed.append("star-navigation")
                    continue

        out.append(block)

    if not removed:
        return False
    rebuild(story, out, removed)
    return True


def clean_payload(payload: dict[str, Any]) -> int:
    stories = payload.get("stories") if isinstance(payload.get("stories"), list) else []
    changed = sum(1 for story in stories if isinstance(story, dict) and clean_story(story))
    payload["publisher_hygiene_schema"] = HYGIENE_SCHEMA
    payload["publisher_hygiene_at"] = datetime.now(timezone.utc).isoformat()
    payload["publisher_hygiene_corrected"] = changed
    return changed


def main() -> int:
    if not NEWS_PATH.exists():
        print("No data/news.json found")
        return 0
    payload = json.loads(NEWS_PATH.read_text(encoding="utf-8"))
    changed = clean_payload(payload)
    NEWS_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Publisher hygiene: {changed} story/stories corrected")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
