from __future__ import annotations

from publisher_hygiene import clean_payload


def rendered(story: dict) -> str:
    parts: list[str] = []
    for block in story.get("content_blocks", []):
        if block.get("type") == "list":
            for item in block.get("items", []):
                parts.append(str(item.get("text") if isinstance(item, dict) else item))
        else:
            parts.append(str(block.get("text") or block.get("caption") or block.get("alt") or ""))
    return " | ".join(parts)


def test_citynews_reader_image_summary_and_google_promo_are_removed() -> None:
    story = {
        "source": "CityNews Canada",
        "title": "Local story",
        "content_blocks": [
            {"type": "paragraph", "text": "The final reported paragraph explains what happened and why the decision matters to local residents."},
            {"type": "heading", "text": "Keep it Factual"},
            {"type": "paragraph", "text": "Add CityNews Toronto as a trusted source on Google to see more local stories from us."},
            {"type": "list", "ordered": False, "items": [
                "Image 1: CityNews Everywhere",
                "Image 2",
                "Image 3,1: Add as a preferred source on Google",
                "Image 4,9",
                "Image 8: 680 News Radio Toronto",
                "Image 18: Rogers Sports & Media - Toronto",
            ]},
            {"type": "heading", "text": "Keep reading"},
        ],
    }
    payload = {"stories": [story]}
    assert clean_payload(payload) == 1
    text = rendered(story)
    assert "final reported paragraph" in text
    assert "Keep it Factual" not in text
    assert "trusted source on Google" not in text
    assert "Image 1" not in text
    assert "Keep reading" not in text


def test_cbc_audio_ui_and_photo_caption_are_removed() -> None:
    caption = (
        "Kathleen Doxtator is the owner and an artist at Guided by Our Gifts, a new pop-up shop in White Oaks Mall. "
        "(Kendra Seguin/CBC News)"
    )
    story = {
        "source": "CBC News London",
        "title": "Local Indigenous vendors open new store",
        "content_blocks": [
            {"type": "paragraph", "text": "Kendra Seguin · CBC News"},
            {"type": "paragraph", "text": "Posted: Sep 03, 2026 5:00 AM EDT | Last Updated: 1 hour ago"},
            {"type": "heading", "text": "Listen to this article"},
            {"type": "paragraph", "text": "Estimated 4 minutes"},
            {"type": "paragraph", "text": "The audio version of this article is generated by AI-based technology. Mispronunciations can occur. We are working with our partners to continually review and improve the results."},
            {"type": "paragraph", "text": caption},
            {"type": "paragraph", "text": "A new store featuring clothing, jewelry and accessories made by local Indigenous vendors is opening inside London's White Oaks Mall."},
        ],
    }
    payload = {"stories": [story]}
    assert clean_payload(payload) == 1
    text = rendered(story)
    assert "Listen to this article" not in text
    assert "Estimated 4 minutes" not in text
    assert "AI-based technology" not in text
    assert "Kendra Seguin · CBC News" not in text
    assert "Posted:" not in text
    assert caption not in text
    assert story["image_caption"] == caption
    assert "A new store featuring clothing" in text


def test_cbc_related_video_text_module_is_removed_without_cutting_article() -> None:
    story = {
        "source": "CBC News London",
        "title": "Local Indigenous vendors open new store",
        "content_blocks": [
            {"type": "paragraph", "text": "Guided by Our Gifts had its soft launch on Monday and will celebrate its grand opening on Saturday with local vendors."},
            {"type": "heading", "text": "WATCH | A look inside Guided by Our Gifts:"},
            {"type": "paragraph", "text": "Looking to shop Indigenous? This mall storefront has you covered"},
            {"type": "paragraph", "text": "47 minutes ago"},
            {"type": "paragraph", "text": "Duration 1:06"},
            {"type": "paragraph", "text": "Guided by Our Gifts is an Indigenous-owned and Indigenous-fronted store opening at White Oaks Mall in London, Ont. A dozen vendors from nearby Indigenous communities are selling their artwork under one roof. CBC's Kendra Seguin speaks with owner Kathleen Doxtator to learn why this store fills a gap for both Indigenous and non-Indigenous communities alike."},
            {"type": "paragraph", "text": "Doxtator has sold her beadwork at community events for several years and said the permanent storefront gives vendors another way to reach customers."},
        ],
    }
    payload = {"stories": [story]}
    assert clean_payload(payload) == 1
    text = rendered(story)
    assert "WATCH |" not in text
    assert "mall storefront has you covered" not in text
    assert "47 minutes ago" not in text
    assert "Duration 1:06" not in text
    assert "CBC's Kendra Seguin speaks with owner" not in text
    assert "permanent storefront gives vendors" in text


def test_globe_diversions_tail_is_terminal() -> None:
    story = {
        "source": "The Globe and Mail",
        "title": "Main story",
        "content_blocks": [
            {"type": "paragraph", "text": "The final real paragraph contains the reporting that belongs to the article and should remain available to readers."},
            {"type": "heading", "text": "Diversions"},
            {"type": "list", "items": ["Crossword", "Sudoku", "Word games"]},
            {"type": "heading", "text": "Latest Videos"},
            {"type": "paragraph", "text": "Watch the latest promoted video from another section of the site."},
        ],
    }
    payload = {"stories": [story]}
    assert clean_payload(payload) == 1
    text = rendered(story)
    assert "final real paragraph" in text
    assert "Diversions" not in text
    assert "Crossword" not in text
    assert "Latest Videos" not in text


def test_normal_editorial_list_is_preserved() -> None:
    story = {
        "source": "Example Publisher",
        "title": "Road closures",
        "content_blocks": [{
            "type": "list",
            "items": [
                "Richmond Street closes Tuesday evening.",
                "Oxford Street has one lane closed Wednesday.",
                "Dundas Street work begins Thursday morning.",
            ],
        }],
    }
    payload = {"stories": [story]}
    assert clean_payload(payload) == 0
    assert story["content_blocks"][0]["type"] == "list"


def main() -> int:
    tests = [
        test_citynews_reader_image_summary_and_google_promo_are_removed,
        test_cbc_audio_ui_and_photo_caption_are_removed,
        test_cbc_related_video_text_module_is_removed_without_cutting_article,
        test_globe_diversions_tail_is_terminal,
        test_normal_editorial_list_is_preserved,
    ]
    for test in tests:
        test()
        print(f"PASS {test.__name__}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
